#! /bin/sh

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

setxkbmap se #Set keyboardlayout

# Startup programs
sh .config/polybar/launch.sh
sh ~/.fehbg
[ $(pid sxhkd) ] && pkill -USR1 sxhkd || sxhkd &

[ $(pidof compton) ] &&
	pkill -USR1 compton ||
	compton --config ~/.config/compton/compton.conf &

volnoti
xss-lock -- i3lock --fuzzy -o

