#! /bin/sh

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config ignore_ewmh_focus true #Don't let applications set focus

# Source device specific configuration
DEVICE_CONF_FILE=$XDG_CONFIG_HOME/.device.bspwm.sh
[ -f $DEVICE_CONF_FILE ] && source $DEVICE_CONF_FILE

setxkbmap se #Set keyboardlayout


# Startup programs
SXHKD_CONFIGS=~/.config/sxhkd/bspwm.sxhkdrc #Alter this to switch wm
SXHKD_SHARED=~/.config/sxhkd/sxhkdrc #This contains non wm-dependent keybinds
[ $(pidof sxhkd | awk '{print $1}') ] && pkill -USR1 sxhkd \
  || exec sxhkd -c $SXHKD_CONFIGS $SXHKD_SHARED &
[ $(pidof picom) ] &&
	pkill -USR1 picom ||
	exec picom --experimental-backends &
exec volnoti &
exec xss-lock -- physlock &
$XDG_CONFIG_HOME/polybar/launch.sh
wal -R
pgrep unclutter || exec unclutter &
pgrep bspwmswallow || exec -a bspwmswallow $XDG_CONFIG_HOME/bspwm/bspwmswallow.sh &

# Move all steam games to a specifed workspace
workspace=9
steamlib=~/.local/share/Steam    # path to your steamlibrary
mygames=$(ls $steamlib/steamapps/appmanifest_*.acf | sed 's/[^0-9]*//g')    # this sed command removes everything but the digits
for game in $mygames; do
    bspc rule -a steam_app_$game desktop=^$workspace state=fullscreen
done

# Rules
bspc rule --add Steam desktop=8 state=tiled
bspc rule --add discord desktop=7 state=tiled
bspc rule --add Zathura state=tiled

bspc config external_rules_command $XDG_CONFIG_HOME/bspwm/external_rules
