#! /bin/sh

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# If there is only monitor connected then assign all desktops to it, otherwise
# split them evenly.
if [ $(xrandr -q | grep " connected " | awk '{print $1}' | wc -l) = 1 ]; then
	bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 0
else
	bspc monitor HDMI1 -d 1 2 3 4 5  
	bspc monitor eDP1 -d 6 7 8 9 0
fi

setxkbmap se #Set keyboardlayout


# Startup programs
SXHKD_CONFIGS=~/.config/sxhkd/bspwm.sxhkdrc #Alter this to switch wm
SXHKD_SHARED=~/.config/sxhkd/sxhkdrc #This contains non wm-dependent keybinds
[ $(pidof sxhkd | awk '{print $1}') ] && pkill -USR1 sxhkd \
  || sxhkd -c $SXHKD_CONFIGS $SXHKD_SHARED &

[ $(pidof picom) ] &&
	pkill -USR1 picom ||
	picom --experimental-backends &

volnoti &
xss-lock -- physlock &
$XDG_CONFIG_HOME/polybar/launch.sh
wal -R
unclutter &
