#! /bin/sh

wid=$1
class=$2
instance=$3
consequences=$4

if [ "$class" = Steam ] ; then
	WM_NAME=$(
		xprop -id $wid -notype -f WM_NAME 8u '=$0' WM_NAME | \
		cut -d '=' -f2 | cut -d'"' -f 2
	)
	# Only the main window seem to have the name "Steam", so this will make any
	# other windows float and be centered
	[ "$WM_NAME" != Steam ] && echo "state=floating center=on"
fi
